version: '3.5'
services:
  school-guardian-backend:
    container_name: school-guardian-backend
    build: .
    restart: always
    ports:
      - '3335:3335'
    volumes:
      - .:/app/school-guardian-backend
      - node-modules-school-guardian-backend:/app/school-guardian-backend/node_modules
    networks:
      - school-guardian-backend-network
      - postgres-network
volumes:
  node-modules-school-guardian-backend:
    name: node-modules-school-guardian-backend
networks:
  school-guardian-backend-network:
    name: school-guardian-backend-network
    driver: bridge
  postgres-network:
    name: postgres-network
    external: true
